---
name: Build Tasmota with OpenTherm support

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: "YamlLint"
        run: |
          docker run \
            --rm \
            -w /repo \
            -v $(pwd):/repo \
            -t \
            alpine:3.20 /bin/sh -c " \
              apk add --no-cache py-pip python3 bash \
              && pip3 install --break-system-packages  yamllint \
              && yamllint -s . \
            "
      - name: "ShellCheck"
        run: |
          docker run \
            --rm \
            -w /repo \
            -v $(pwd):/repo \
            -t \
            alpine:3.20 /bin/sh -c " \
              apk add --no-cache shellcheck bash \
              && shellcheck $(find . -type f -name "*.sh" |  tr '\n' ' ')
            "
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: "Build Tasmota"
        run: ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release gnome ${{ github.ref }}
          draft: true
          files: |
            ./release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # You don't need to add this in secrets it's by default.
